name: aivision_privacy_15
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.11.26=haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py310haa95532_0
  - python=3.10.15=h4607a30_1
  - setuptools=75.1.0=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h0416ee5_0
  - vc=14.40=haa95532_2
  - vs2015_runtime=14.42.34433=h9531ae6_2
  - wheel=0.44.0=py310haa95532_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - albucore
      - albumentations
      - annotated-types==0.7.0
      - anyio==4.7.0
      - astunparse==1.6.3
      - cachetools==5.5.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.11
      - easydict==1.13
      - eval-type-backport==0.2.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.6
      - ffmpy==0.4.0
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fonttools==4.55.2
      - fsspec==2024.10.0
      - gast==0.4.0
      - google-auth==2.36.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - gradio==5.5.0
      - gradio-client==1.4.2
      - grpcio==1.68.1
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.28.0
      - huggingface-hub==0.26.3
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.36.1
      - insightface==0.7.3
      - jax==0.4.36
      - jaxlib==0.4.36
      - jinja2==3.1.4
      - joblib==1.4.2
      - keras==2.12.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.3
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - onnx==1.16.0
      - onnxruntime-gpu==1.16.3
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.10.0.84
      - opt-einsum==3.4.0
      - orjson==3.10.12
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - prettytable==3.12.0
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pyparsing==3.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - ruff==0.8.2
      - safehttpx==0.1.6
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - simsimd==6.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - stringzilla==3.11.0
      - sympy==1.13.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tomlkit==0.12.0
      - torch==2.0.1+cu118 
      - torchaudio==2.0.2+cu118
      - torchvision==0.15.2+cu118
      - tqdm==4.67.1
      - typing-extensions
      - typer==0.15.1
      - tzdata==2024.2
      - urllib3==2.2.3
      - uvicorn==0.32.1
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.1.3
      - wrapt==1.14.1
prefix: C:\Users\user\anaconda3\envs\aivision_privacy
